PanGamez/Controllers/CPFijoController.cs
using Microsoft.AspNetCore.Mvc;
using PanGamez.Models;

namespace PanGamez.Controllers
{
    public class CPFijoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult Calculate(CPfijo model)
        {
            if (ModelState.IsValid)
            {
                int D = model.Demanda;

                int Q = model.InventarioPedido;

                int SS = model.InventarioSeguridad;

                //Calcular Costo Promedio por Fijo
                int I = (Q / 2) + SS;

                //Calculo de retacion de inventario
                int RotacionInventario = D / I;

                string analisisRespuesta = $"El costo promedio fijo es de: {I}." +
                    $" La rotacion de inventario es: {RotacionInventario}.";

                //Pasando resultados a la vista desde este controlador
                ViewData["CPfijo"] = analisisRespuesta;

                return View("Index", model);
            }
            else
            {
                //Si el modelo no es valido, muestra errores y formulario
                return View("Index", model);
            }
        }
    }
}

PanGamez/Controllers/EoqController.cs
using Microsoft.AspNetCore.Mvc;
using PanGamez.Models;

namespace PanGamez.Controllers
{
    public class EoqController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        // POST: EOQ/Calculate
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Calculate(EOQ model)
        {
            if (ModelState.IsValid)
            {
                double D = model.Demanda;
                double S = model.CostoPedido;
                double H = model.CostoMantenimiento;
                double periodo = model.PeriodoSeleccionado;

                // Calcular EOQ
                double EOQ = Math.Sqrt((2 * D * periodo * S) / H);
                int eoqInt = (int)Math.Round(EOQ);
                string analysis = $"La cantidad de pedidos que la empresa deberá realizar es de {eoqInt} unidades para que el inventario no se agote durante el tiempo de entrega.";

                // Pasar el resultado a la vista
                ViewData["EOQ"] = analysis;
                ViewData["Resultado"] = eoqInt;

                return View("Index", model);
            }
            else
            {
                // Si el modelo no es válido, volver a mostrar el formulario con los errores
                return View("Index", model);
            }
        }
    }
}

PanGamez/Controllers/LtcController.cs
using Microsoft.AspNetCore.Mvc;
using PanGamez.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace PanGamez.Controllers
{
    public class LtcController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CalculateLTC(int numeroPeriodos, string requerimientosBrutos, double costoOrdenar, double costoMantenimiento)
        {
            var results = new List<LTC>();

            // Convertir la cadena de requerimientos brutos en una lista de enteros
            var unidades = requerimientosBrutos.Split(',').Select(int.Parse).ToList();

            // Inicializamos los valores para el primer período
            var periodo = 0;
            var unidadesPeriodo = unidades[0];
            var periodosMantenidos = 0;
            var costoMantenimientoAcumulado = 0.0;

            // Iteramos sobre cada período
            for (int i = 0; i < numeroPeriodos; i++)
            {
                // Calculamos el costo de mantenimiento para el período actual
                var costoMantenimientoPeriodo = unidadesPeriodo * periodosMantenidos * costoMantenimiento;

                // Calculamos el costo de mantenimiento acumulado
                costoMantenimientoAcumulado += costoMantenimientoPeriodo;

                // Guardamos los resultados en la lista
                results.Add(new LTC
                {
                    Periodo = periodo,
                    Unidades = unidadesPeriodo,
                    PeriodosMantenidos = periodosMantenidos,
                    CostoMantenimiento = costoMantenimientoPeriodo,
                    CostoMantenimientoAcumulado = costoMantenimientoAcumulado
                });
                // Si el costo de mantenimiento acumulado supera el costo de ordenar, reiniciamos los valores
                if (costoMantenimientoAcumulado >= costoOrdenar)
                {
                    periodo = 1;
                    periodosMantenidos = 0;
                    costoMantenimientoAcumulado = 0.0;
                }
                else
                {
                    // Avanzamos al siguiente período
                    periodo++;
                    periodosMantenidos++;
                }

                // Actualizamos las unidades para el próximo período
                if (i < unidades.Count - 1)
                {
                    unidadesPeriodo = unidades[i + 1];
                }
            }
            ViewBag.CostoOrdenar = costoOrdenar;
            // Retornamos la vista con los resultados
            return View("Index", results);
        }
    }
}

PanGamez/Controllers/LucController.cs
using Microsoft.AspNetCore.Mvc;
using PanGamez.Models;
using Microsoft.AspNetCore.Mvc;
using PanGamez.Models;
using System;
using System.Collections.Generic;
using System.Linq;
namespace PanGamez.Controllers
{
    public class LucController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CalculateLUC(int Periodo, string RequerimientoBruto, double costoDeOrdenar, double costoMantenimiento)
        {
            var results = new List<LUC>();

            // Convertir la cadena de requerimientos brutos en una lista de enteros
            var unidades = RequerimientoBruto.Split(',').Select(int.Parse).ToList();

            // Inicializamos los valores para el primer período
            var periodo = 0;
            var unidadesPeriodo = unidades[0];
  
            bool primeraIteracion = true; // Bandera para identificar la primera iteración
            int sumaAnterior = 0;
            int sumaAnteriorRequerimiento = 0;
            double sumaAnteriorK = 0;
            double costoTotal;
            double costoTotalAnterior = 0; // Variable para almacenar el costoTotal anterior



            // Iteramos sobre cada período
            for (int i = 0; i < Periodo; i++)
            {

                // Obtenemos el valor de la fila actual
                var periodoActual = unidades[i];

                // Sumamos el valor actual con el valor de la fila anterior, si existe


                // Calculamos el costo de mantenimiento para el período actual
                var costoMantenimientoPeriodo = costoMantenimiento;



                var sumaConAnterior = (i +1) + sumaAnterior;
                sumaAnterior = sumaConAnterior;
                var sumaConAnteriorRequerimiento = unidadesPeriodo + sumaAnteriorRequerimiento;
                sumaAnteriorRequerimiento = sumaConAnteriorRequerimiento;

                if (primeraIteracion)
                {
                    sumaAnteriorK = 0; // Primera multiplicación con cero
                    primeraIteracion = false; // Desactivar la bandera después de la primera iteración
                    costoTotalAnterior = costoDeOrdenar;

                }

                else
                {
                    var SumaConAnteriorK = costoMantenimiento * sumaConAnterior * ((i+1) - 1);
                    sumaAnteriorK = SumaConAnteriorK;
                    costoTotal = costoTotalAnterior + sumaAnteriorK; // Sumar costoTotalAnterior con sumaAnteriorK
                    costoTotalAnterior = costoTotal; // Actualizar costoTotalAnterior
                }




                // costoTotal = item.costoDeOrdenar + sumaAnteriorK;
                var costoTotalUnidades = costoTotalAnterior / sumaConAnteriorRequerimiento;



                // Guardamos los resultados en la lista
                results.Add(new LUC
                {
                    Periodo = sumaConAnterior,
                    RequerimientoBruto = sumaConAnteriorRequerimiento,
                    costoDeOrdenar = costoDeOrdenar,
                    CostoMantenimiento = sumaAnteriorK,
                    CostoTotal = costoTotalAnterior,
                    CostoUTotalU = costoTotalUnidades
                }); ;
                
                // Actualizamos las unidades para el próximo período
                if (i < unidades.Count - 1)
                {
                    unidadesPeriodo = unidades[i + 1];
                }
            }
            ViewBag.CostoOrdenar = costoDeOrdenar;
            // Retornamos la vista con los resultados
            return View("Index", results);
        }
    }
}

PanGamez/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Calculadora de Métodos - PanGamez</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PanGamez.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/logo.jpg" alt="Logo PanGamez" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Metodos - 1era Unidad
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="CostoMantenimiento" asp-action="Index">Mantenimiento</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Eoq" asp-action="Index">EOQ</a>
                                <a class="dropdown-item" asp-area="" asp-controller="CPFijo" asp-action="Index">Costo Promedio Fijo</a>
                                <a class="dropdown-item" asp-area="" asp-controller="CPStock" asp-action="Index">Costo Promedio Stock</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Ltc" asp-action="Index">LTC</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Luc" asp-action="Index">LUC</a>

                            </div>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PanGamez - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>